### ISSUE TITLE
1.34.2 support

### ISSUE THREAD

**Issue by Reonu** [HypersonicSharkz/SmartSongSuggest#2]
The modding community is migrating to 1.34.2 as the new recommended version. I would love to upgrade, but without this addon, it's a non-starter. It would be cool if it was upgraded to work on 1.34.2 :)

**Comment by TaohRihze** [comment]
https://github.com/HypersonicSharkz/SmartSongSuggest/releases/tag/v2.0.0a Test version that works with 1.34.2

**Comment by TaohRihze** [comment]
Prerelease versions are best option for now. Added 1.37.0 prerelease as well. These are fully functional versions, may contain partial features, and minor bugs. (hopefully only minor).

Full releases are reserved for polished versions that are being attempted to be pushed to the mod installers.
