### ISSUE TITLE
1.37.0 or 1.37.1 support?

### ISSUE THREAD

**Issue by puppy65po** [HypersonicSharkz/SmartSongSuggest#5]
Will there be support for 1.37.0 and 1.37.1 sometime?

**Comment by TaohRihze** [comment]
Test Branch has a working 1.37.0. But the moving goalpost of mods to submit are at 1.37.1 atm, so no place to post it currently. Had hoped to have a stable base (I could use as well) to develop it on. So trying to figure out how to approach this.

1.37.0 mod will be shared here likely.

**Comment by TaohRihze** [comment]
Prerelease versions are best option for now. Added 1.37.0 prerelease as well. These are fully functional versions, may contain partial features, and minor bugs. (hopefully only minor).

Full releases are reserved for polished versions that are being attempted to be pushed to the mod installers.
