### ISSUE TITLE
Game keeps crashing apon starting - 1.37.0

### ISSUE THREAD

**Issue by puppy65po** [HypersonicSharkz/SmartSongSuggest#6]
I have just installed the prerelease of the 1.37 mod and every time i launch the game it crashes! I have tried to reinstall the mod and it still crashes. 
[_latest.log](https://github.com/user-attachments/files/16638832/_latest.log)
 

> [CRITICAL @ 11:30:27 | IPA] Type 'SmartSongSuggest.Configuration.PluginConfig' implements INotifyPropertyChanged but does not have an accessible 'RaisePropertyChanged(string)' method, automatic raising of PropertyChanged event is disabled.

**Comment by TaohRihze** [comment]
I get the same error, but I am able to use the mod without issues.
```[CRITICAL @ 22:52:12 | IPA] Type 'SmartSongSuggest.Configuration.PluginConfig' implements INotifyPropertyChanged but does not have an accessible 'RaisePropertyChanged(string)' method, automatic raising of PropertyChanged event is disabled.```

I do not think the issues is related to above error, as I got it as well and the mod started, and the disabled function should not be used if I recall what Sharkz told me correctly.

---

You seem to have all dependencies as well, did you place the SongSuggestCore.dll in the Libs folder? (not Plugins).

Is there a folder for SmartSongSuggest in your UserData, as well as the SmartSongSuggest.json file (in the top folder)?

If so, please try and enable additional logging by editing SmartSongSuggest.json (notepad) by turning LogEnabled to true like this

```
  "__comment_Config_Options__": "Logging Enabled",
  "LogEnabled": true,
```

Should show a bit more where it stalls out during load. If you could attach another log with the extra information I might be able to get an idea when it crashes during load (if that is the case).

**Comment by TaohRihze** [comment]
Feel free to msg me on Discord. 
`.taoh`

**Comment by TaohRihze** [comment]
Looking at the logs again, I think it is that you placed of the SongSuggestCore in Plugins, instead of Libs.

I get this info on load

> [DEBUG @ 22:52:12 | IPA/LibraryLoader] Resolving library SongSuggestCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

While yours says

> [NOTICE @ 11:30:23 | IPA/Loader] No manifest.json in SongSuggestCore.dll

I am closing this issue for now, if I am wrong, do reopen, and let me know :)
